version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server


  # Database service
  mongodb:
    container_name: mongodb_database
    image: mongo:latest
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./mydata:/data/db
    ports:
      - "27018:27017"


# Volumes define
volumes:
  mydata: